### ISSUE TITLE
What is the appropriate image size for segment.py?

### ISSUE THREAD

**Issue by LittleWat** [fyu/drn#11]
Hello. 
Thank you for a nice implementation!

I would like to know what image size works well when applying segmentation.
If we use Cityscapes, original size is 2048x1024. Should we use the original size?

**Comment by fyu** [comment]
The training crop sizes are suggested here: https://github.com/fyu/drn#training
At inference time, you can use the original image size.

**Comment by LittleWat** [comment]
Thank you for answering!
I see. The larger, the better. I will try :) Thanks!
