### ISSUE TITLE
Will pre-trained classification model will be shared?

### ISSUE THREAD

**Issue by Ai-is-light** [fyu/drn#18]
@fyu Thanks for your excellent work about the about the dilated convolution and using this technique combined with the residual network. And, I would like to know whether you will share the pre-trained classification model for us, I would like to use your classification model in the field of pose estimation.
Looking forward your classification model

**Comment by fyu** [comment]
Yes. It is already shared in pytorch model zoo. Check here: https://github.com/fyu/drn/issues/17
