### ISSUE TITLE
about train_images.txt

### ISSUE THREAD

**Issue by amiltonwong** [fyu/drn#3]
Hi, @fyu ,

Thanks for releasing drn. For the training on Cityscapes dataset, train_images.txt / train_labels.txt are required and they are explained in readme. Could you upload these files or could we download them in Cityscapes official site?

Thanks!

**Comment by abursuc** [comment]
You can generate them easily yourself in your shell. Here' s an example for generating train_images.txt in your cityscapes folder:

```
find leftImg8bit/train -maxdepth 3 -name "*_leftImg8bit.png" | sort | > train_images.txt
```

**Comment by amiltonwong** [comment]
Thanks @abursuc

**Comment by abursuc** [comment]
Hi.
You may close the issue if your problem has been solved using the suggestion above.

**Comment by fyu** [comment]
Please check here for full description of preparing Cityscapes data: https://github.com/fyu/drn/tree/master/datasets/cityscapes
