### ISSUE TITLE
Upload pretrained DRN models as they no longer seem available on the Princeton website

### ISSUE THREAD

**Issue by jakubLangr** [fyu/drn#52]
Hello @fyu — I am not sure if you moved institutions—if so, congratulations!—but the URLs for the pretrained models all return 404s, even at the root URL. 

Would it be possible to upload them to e.g. GDrive along the Cityscape ones? I need them for replicating some downstream work :) 

Hope you had good holidays! 

Best,

**Comment by fyu** [comment]
The model has been moved to a new server, as in the current code: https://github.com/fyu/drn/blob/master/drn.py#L13

**Comment by jakubLangr** [comment]
Hi @fyu , thank you so much for such a wonderful and prompt response! 

Apologies, I was using a version from another work that still included older version of the code. After the changes, the models download.

However, now I have an issue that looks like there is a mismatch between how many semantic classes / channels the model expects. As there is the typical 19 COCO vs 1000 channels. Maybe PyTorch loads it differently? I am using 1.1.0, so maybe it's too new:

```
RuntimeError: Error(s) in loading state_dict for DRN:
	size mismatch for fc.weight: copying a param with shape torch.Size([1000, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([19, 512, 1, 1]).
	size mismatch for fc.bias: copying a param with shape torch.Size([1000]) from checkpoint, the shape in current model is torch.Size([19]).
```
