### ISSUE TITLE
Does the weight(drn_d_105-12b40979.pth) only train on ImageNet?

### ISSUE THREAD

**Issue by johnnylu305** [fyu/drn#54]
I am working on weakly-supervised semantic segmentation. 
I used drn-d-105 as our backbone for deeplabv2 and it worked very well.
During training, I load drn_d_105-12b40979.pth as our pretrained weight from this [website](http://dl.yf.io/drn/).
Does the weight(drn_d_105-12b40979.pth) only train on ImageNet?
I have to make sure the weight is not related to other non-image level labels.

**Comment by fyu** [comment]
Yes, the model drn_d_105 was only trained on imagenet
